### ISSUE TITLE
Optimize size of generated dataset

### ISSUE THREAD

**Issue by rchl** [woothee/woothee-js#12]
I've looked at this package because its size seemed fairly big. I've noticed one thing that could possibly be optimized. This code seems to create a object in fairly inefficient way (byte size wise):
https://github.com/woothee/woothee-js/blob/3e4514ce70162cf7c8ec58c80b72e6d8c8192e7d/scripts/dataset_yaml2js.js#L31-L47

I wonder why it's not creating a JS object instead, and just call `JSON.stringify` on it. That should make resulting data size a bit smaller.

**Comment by tagomoris** [comment]
That might be smaller because of less JS code (assignment, variable name, etc), but that might be bigger because of additional double quotes (`"`) for keys.
Did you actually created it and measure the size difference?
The patch to do that is welcome if there were a big difference.

**Comment by rchl** [comment]
Good point, didn't think of that. But after quick search I found https://github.com/commenthol/serialize-to-js which serializes to JS object so without extra quotes. With that implemented, size of dataset.js went down from 52471 bytes to 10475 bytes.
I'll submit PR for it.

**Comment by rchl** [comment]
BTW. Another thing where some bytes could be shaved off would be replacing all `indexOf('...') >= 0` with `includes('...')`. The only thing is that `includes` is supported since node 4 and I'm not sure what is minimal node version you are targeting with this package. To be on the safe size, this could be done in next major version with node requirement set to v4 explicitly.

**Comment by tagomoris** [comment]
This implementation is not only for Node.js, but also for many Javascript implementations on browsers. I found that a document (of Mozilla) says `String.prototype.includes` was supported by ECMAScript 2015, but I'm unsure how it's common.
Do you have any idea about it?

For example, IE does not support it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

**Comment by rchl** [comment]
Right, due to IE11 it probably shouldn't be done...

The solution could be to have multiple versions of library that would be auto-generated with babel for different targets. But that would be bigger task and not sure it would be worth it.
