### ISSUE TITLE
woothee.isCrawler always returns false

### ISSUE THREAD

**Issue by hokaccha** [woothee/woothee-js#16]
https://github.com/woothee/woothee-js/blob/eb44a52e074f46395ed8d4b4367176333b9b09a6/lib/woothee.js#L18-L20

Is this function not yet implemented?

**Comment by tagomoris** [comment]
Oh, I guess I would implement it later (but forget it...)

**Comment by tagomoris** [comment]
@hokaccha Do you need the released version with this feature immediately?

**Comment by hokaccha** [comment]
Yes, I need it!

**Comment by tagomoris** [comment]
Ship it https://www.npmjs.com/package/woothee/v/1.11.1
Thanks for your contribution!

**Comment by hokaccha** [comment]
Thanks!
